#!/bin/bash

set -e

if [ ! -f "./.env" ]; then
  echo "File \"./.env\" doesn't exist"
  echo "Please create the file and fill the following items: \
    AZURE_SUBSCRIPTION_ID='***'
    RESOURCE_GROUP_NAME='***'
    AZURE_FUNCTION_NAME='***'
    AZURE_LOCATION='***'
    GH_REPOSITORY='***/***'
    "
  exit 1
fi

set -o allexport; source .env; set +o allexport

GH_SUBJECT="repo:${GH_REPOSITORY}:ref:refs/heads/main"

az account set --subscription ${SUBSCRIPTION_ID}
az group create -n ${RESOURCE_GROUP_NAME} -l ${AZURE_LOCATION}

AAD_APP=$(az ad app create --display-name ${AZURE_FUNCTION_NAME} -o json)
APP_OID=$(echo ${AAD_APP} | jq -r ".id")
APP_ID=$(echo ${AAD_APP} | jq -r ".appId")

az ad sp create --id ${APP_OID}
SPN_OID=$(az ad sp show --id ${APP_ID} -o tsv --query "id")

az role assignment create \
  --role contributor \
  --scope ${AKS_RESOURCE_ID} \
  --assignee-object-id ${SPN_OID} \
  --assignee-principal-type ServicePrincipal \
  > /dev/null

az rest \
  --method POST \
  --uri "https://graph.microsoft.com/beta/applications/${APP_OID}/federatedIdentityCredentials" \
  --body "{\"name\":\"${APP_DISPLAYNAME}\",
          \"issuer\":\"https://token.actions.githubusercontent.com\",
          \"subject\":\"${GH_SUBJECT}\"
          ,\"description\":\"Federated credenital on GitHub actions\",
          \"audiences\":[\"api://AzureADTokenExchange\"]}"

# TODO #
# get AZURE_TENANT_ID
# get AZURE_CLIENT_ID

# TODO #
# output the following: 
# - AZURE_APP_NAME
# - AZURE_CLIENT_ID
# - AZURE_RESOURCE_GROUP
# - AZURE_SUBSCRIPTION_ID
# - AZURE_TENANT_ID
