#!/bin/bash

set -e
if [ ! -f "./.env" ]; then
  echo "File \"./.env\" doesn't exist. Please create the file and fill the following items: 
    AZURE_FUNCTION_NAME='***'
    AZURE_LOCATION='***'
    AZURE_RESOURCE_GROUP='***'
    AZURE_SUBSCRIPTION_ID='***'
    AZURE_TENANT_ID='***'
    GH_REPOSITORY='***/***'
    "
  exit 1
fi

set -o allexport; source ./.env; set +o allexport

GH_SUBJECT="repo:${GH_REPOSITORY}:ref:refs/heads/main"

az account set --subscription ${AZURE_SUBSCRIPTION_ID}
az group create -n ${AZURE_RESOURCE_GROUP} -l ${AZURE_LOCATION}

AAD_APP=$(az ad app create --display-name ${AZURE_FUNCTION_NAME} -o json)
APP_OID=$(echo ${AAD_APP} | jq -r ".id")
APP_ID=$(echo ${AAD_APP} | jq -r ".appId")

az ad sp create --id ${APP_OID}
SPN_OID=$(az ad sp show --id ${APP_ID} -o tsv --query "id")

AZ_SCOPE="subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${AZURE_RESOURCE_GROUP}" 

az role assignment create \
  --role contributor \
  --scope ${AZ_SCOPE} \
  --assignee-object-id ${SPN_OID} \
  --assignee-principal-type ServicePrincipal \
  > /dev/null

AZURE_CLIENT_ID=$(az rest \
  --method POST \
  --uri "https://graph.microsoft.com/beta/applications/${APP_OID}/federatedIdentityCredentials" \
  --body "{\"name\":\"${AZURE_FUNCTION_NAME}\",
          \"issuer\":\"https://token.actions.githubusercontent.com\",
          \"subject\":\"${GH_SUBJECT}\"
          ,\"description\":\"Federated credenital on GitHub actions\",
          \"audiences\":[\"api://AzureADTokenExchange\"]}" \
          | jq -r ".appId")

echo "Add the following secrets to Github: 
    AZURE_CLIENT_ID: ${AZURE_CLIENT_ID} 
    AZURE_FUNCTION_NAME: ${AZURE_FUNCTION_NAME} 
    AZURE_RESOURCE_GROUP: ${AZURE_RESOURCE_GROUP} 
    AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID} 
    AZURE_TENANT_ID: ${AZURE_TENANT_ID} 
    "